services:
  ms-order-receiver-app:
    image: evandroig/ms-order-receiver:latest
    networks:
      - "ms-order-receiver-network"
    ports:
      - "8080:8080"
    depends_on:
      - "kafka"
    environment:
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  kafka:
    image: apache/kafka:latest
    networks:
      - "ms-order-receiver-network"
    ports:
      - "9092:9092"
networks:
  ms-order-receiver-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"